---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bicarahu/public_html/
    - rm -rf $DEPLOYPATH/*
    - npm ci --no-audit --no-fund
    - npm run export
    - /bin/cp -R out/* $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH