[build]
  command = "npm install --include=dev && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

# Plugin untuk Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Konfigurasi domain
[context.production]
  domain = "bicarahukum.my.id"

# Redirect untuk www subdomain
[[redirects]]
  from = "https://www.bicarahukum.my.id/*"
  to = "https://bicarahukum.my.id/:splat"
  status = 301
  force = true

# Redirect untuk HTTP ke HTTPS
[[redirects]]
  from = "http://bicarahukum.my.id/*"
  to = "https://bicarahukum.my.id/:splat"
  status = 301
  force = true

# Headers untuk keamanan
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Auto deploy configuration
[build.processing]
  skip_processing = false

# Environment variables untuk auto deploy
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_NAME = "Melek Hukum ID"
  NEXT_PUBLIC_SITE_URL = "https://bicarahukum.my.id"
  NEXT_PUBLIC_BASE_URL = "https://bicarahukum.my.id"
  NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-D5EH0QKDSF" 